### ISSUE TITLE
初始化不set数据的问题

### ISSUE THREAD

**Issue by bailibaili** [baoyongzhang/Treasure#10]
如果我初始化后，不set任何数据，然后用get方法拿数据的话总会崩溃，加任何判断都没用；整个应用中我们不能保证只在set之后拿数据吧？这个问题应该怎么解决呢？想请教一下

**Comment by bailibaili** [comment]
用application的Context拿不到实例，是这样么？

**Comment by baoyongzhang** [comment]
方便贴一下代码段吗，我这里测试没发现

**Comment by bailibaili** [comment]
final SimplePreferences preferences = Treasure.get(getBaseContext(), SimplePreferences.class, "test");
        Log.d("Ls", (preferences==null)+ "");
        User person = new User();
        person.name = "Mr.Bao";
        person.age = 21;
        preferences.setPerson(person);
        Log.d("Ls", preferences.getPerson().toString());

        preferences.removePerson();

        User person2 = preferences.getPerson();
        Log.d("Ls", (null == person2) + "");

实验了一下，在application中这样会有问题

**Comment by baoyongzhang** [comment]
崩溃的异常堆栈是啥？

**Comment by bailibaili** [comment]
java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4591)
                                                                        at android.app.ActivityThread.access$1500(ActivityThread.java:154)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5298)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
                                                                        at android.util.Base64.decode(Base64.java:118)
                                                                        at com.baoyz.treasure.SimpleConverterFactory$2.convert(SimpleConverterFactory.java:63)
                                                                        at com.baoyz.treasure.SimpleConverterFactory$2.convert(SimpleConverterFactory.java:59)
                                                                        at com.baoyz.treasure.SimplePreferences__Treasure.getPerson(SimplePreferences__Treasure.java:70)
                                                                        at com.baoyz.treasure.MyApp.onCreate(MyApp.java:24)
                                                                        at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:369)
                                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
                                                                        at android.app.ActivityThread.access$1500(ActivityThread.java:154) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:135) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5298) 
                                                                        at java.lang.reflect.Method.invoke(Native Method)

**Comment by baoyongzhang** [comment]
User 如果没有实现 Serializable 或者 Parcelable 接口，默认是不支持的，你需要自定义 Converter。 README 里面有一个用 GSON 去序列化的 Converter 的例子。你看看你是不是这个问题

**Comment by bailibaili** [comment]
不是的，这个user是实现Serializable 的，就是你demo中的user
public class User implements Serializable {

    public User() {
    }

    public User(String name, int age) {
        this.name = name;
        this.age = age;
    }

    public String name;
    public int age;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        User person = (User) o;

        if (age != person.age) return false;
        return !(name != null ? !name.equals(person.name) : person.name != null);

    }

    @Override
    public int hashCode() {
        int result = name != null ? name.hashCode() : 0;
        result = 31 * result + age;
        return result;
    }
}

**Comment by bailibaili** [comment]
实验了几种情况，发现# 只在application中实例化一次，并且不set数据，在activity中直接拿会有问题

**Comment by baoyongzhang** [comment]
我大概知道问题了，正在尝试解决

**Comment by bailibaili** [comment]
好的

**Comment by baoyongzhang** [comment]
试一下 0.7.1 版本

**Comment by bailibaili** [comment]
好，稍等

**Comment by bailibaili** [comment]
您好，现在初始化没有报错了，还没有测试其他是否正常，多谢

**Comment by baoyongzhang** [comment]
好的，有问题随时提 issue

**Comment by bailibaili** [comment]
能说一下大概的问题所在么？

**Comment by baoyongzhang** [comment]
问题是 SimpleConverter 里没加 非空 判断 = =!，SP 本身支持的数据类型没有这个问题，对象序列化才会用到 SImpleConverter，是我测试没覆盖到。
